name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  security-events: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify source files
        run: |
          ls -la
          test -f main.c || (echo "main.c not found" && exit 1)

      - name: Prepare reports and compile_commands.json
        run: |
          mkdir -p reports
          SRC_FILE=$(realpath main.c)
          SRC_DIR=$(dirname "$SRC_FILE")
          echo '[' > compile_commands.json
          echo '{' >> compile_commands.json
          echo '  "directory": "'"$SRC_DIR"'",' >> compile_commands.json
          echo '  "command": "gcc -std=c17 -I. -O2 -c main.c",' >> compile_commands.json
          echo '  "file": "'"$SRC_FILE"'"' >> compile_commands.json
          echo '}' >> compile_commands.json
          echo ']' >> compile_commands.json
          cat compile_commands.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=my_project_key
            -Dsonar.organization=my_org
            -Dsonar.sources=.
            -Dsonar.cfamily.compile-commands=compile_commands.json
            -Dsonar.sarifReportPaths=reports/trivy.sarif,reports/semgrep.sarif
