name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  security-events: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify source files
        run: |
          if [ ! -f "./main.c" ]; then
            echo "main.c not found at root. Failing."
            exit 1
          fi

      - name: Prepare reports directory and compile_commands.json
        run: |
          mkdir -p reports
          ABS_PATH=$(realpath main.c)
          DIR_PATH=$(dirname "$ABS_PATH")
          echo '[' > compile_commands.json
          echo '  {' >> compile_commands.json
          echo '    "directory": "'"$DIR_PATH"'",' >> compile_commands.json
          echo '    "command": "gcc -std=c17 -I'"$DIR_PATH"' -O2 -g main.c -o main",' >> compile_commands.json
          echo '    "file": "'"$ABS_PATH"'"' >> compile_commands.json
          echo '  }' >> compile_commands.json
          echo ']' >> compile_commands.json

      - name: Debug compile_commands.json
        run: cat compile_commands.json

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: sarif
          output: reports/trivy.sarif
          exit-code: 0

      - name: Install Semgrep CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: python3 -m pip install --upgrade semgrep

      - name: Run Semgrep scan
        run: semgrep --config p/ci --sarif --output reports/semgrep.sarif .

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: |
            -Dsonar.login=${{ env.SONAR_TOKEN }}
            -Dsonar.sarifReportPaths=reports/trivy.sarif,reports/semgrep.sarif
            -Dsonar.cfamily.compile-commands=compile_commands.json
