name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  security-events: write

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare reports directory and compile_commands.json
        run: |
          mkdir -p reports
          cat <<EOF > compile_commands.json
          [
            {
              "directory": "/github/workspace",
              "command": "gcc -std=c17 -I/github/workspace -O2 -g /github/workspace/main.c -o main",
              "file": "/github/workspace/main.c"
            }
          ]
          EOF


      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: sarif
          output: reports/trivy.sarif
          exit-code: 0

      - name: Install Semgrep CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: python -m pip install --upgrade semgrep

      - name: Run Semgrep scan
        run: semgrep --config p/ci --sarif --output reports/semgrep.sarif .

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: |
            -Dsonar.sarifReportPaths=reports/trivy.sarif,reports/semgrep.sarif
            -Dsonar.cfamily.compile-commands=compile_commands.json
